CREATE TABLE IF NOT EXISTS cloud_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  public_id TEXT NOT NULL UNIQUE,
  category TEXT DEFAULT '云端',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);